
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
            python-version: 3.8
            
      - name: Install dependencies
        run: |
          make install
          
      - name: Lint with pylint
        run: |
          make lint
          
      - name: Test with pytest
        run: |
          make test
          
      - name: Format code
        run: |
          make format

      - name: Configure AWS credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AMZ ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, Tag, Push Container To ECR
        run: |
          make deploy

          
